### ISSUE TITLE
Add Assistant to JSON Editor

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/nr-assistant#10]
### Description

The "Ask FlowFuse" feature in the function node is _excellent_, it would be great to also see this evolve into the JSON editor too, especially in the "Inject" cloud.

```[tasklist]
### Tasks
- [ ] https://github.com/FlowFuse/nr-assistant/issues/13
- [ ] https://github.com/FlowFuse/flowfuse/issues/4126
- [ ] https://github.com/FlowFuse/website/issues/2346
```
